//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.8.3928.0.
// 
namespace CoreWCF.WebService
{
    using System.Threading.Tasks;
    using CoreWCF;

    [ServiceContract(Namespace = Namespaces.Service)]
    public interface ITheService
    {

        [OperationContract]
        TheResponseType CheckSomeThing(TheServiceRequestType request);
    }

    [ServiceContract(Namespace = Namespaces.Service)]
    public interface ITheServiceAsync
    {

        [OperationContract]
        Task<TheResponseType> CheckSomeThingAsync(TheServiceRequestType request);
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = Namespaces.Service)]
    [MessageContract(IsWrapped = true, WrapperName = "TheServiceRequest", WrapperNamespace = Namespaces.Service)]
    public class TheServiceRequestType
    {
        [MessageBodyMember(Order = 0)]
        public bool BoolValue
        {
            get;
            set;
        }

        [MessageBodyMember(Order = 1)]
        public string StringValue
        {
            get;
            set;
        }
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = Namespaces.Service)]
    [MessageContract(IsWrapped = true, WrapperName = "TheResponse", WrapperNamespace = Namespaces.Service)]
    public class TheResponseType
    {
        [MessageBodyMember(Order = 0)]
        public bool BoolValue
        {
            get;
            set;
        }

        [MessageBodyMember(Order = 1)]
        public string StringValue
        {
            get;
            set;
        }
    }
}